//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Flickr .Net Api Library")]
[assembly: AssemblyDescription(".Net library for accessing Flickr.com Api functionality")]
[assembly: AssemblyCompany("http://flickrnet.codeplex.com")]
[assembly: AssemblyProduct("Flickr .Net Api Library")]
[assembly: AssemblyCopyright("Copyright © Sam Judson 2010")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: AssemblyVersion("3.1.3995.0")]


